### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by deshneni-akhil** [MaheshtheDev/Splitrck#15]
Can you set up an option to send the snapshot or to download the stats as pdf of a certain month this helps to share this information.

**Comment by MaheshtheDev** [comment]
@deshneni-akhil , Able to share stats as snapshot has been to added and its live.

And i added docs regarding that feature here ⬇︎
https://github.com/MaheshtheDev/Splitrck/wiki/Share-your-Stats

Thanks for the Suggestion. Hope this feature will helps you and lemme know if you face any issues

**Comment by deshneni-akhil** [comment]
Thanks for integrating and publishing the FR, I have tested it its working you can close this issue.

**Comment by MaheshtheDev** [comment]
wonderful! feel free to raise any issue or feature request if you face any in future.
